### ISSUE TITLE
Evaluation 

### ISSUE THREAD

**Issue by OmarMohammed88** [CONE-MT/MindMerger#1]
thank u for this wonderful work.
i was wondering what is the GPU requirements to be able to run the evaluation script, i have looked into the code and it gives OOM and after debugging i found u loading the model on a single GPU. i tried to set the device_map = 'auto' to the models but raise another error for loading two vectors on different devices [GPU, CPU].

Any solution for this issue?

**Comment by HuangZixian** [comment]
Thank you for your attention! 

We evaluated our model on a single A100 GPU. When the "--eval_batch_size" is set to 8, GPU Memory-Usage is 79G, and when the "--eval_batch_size"  is set to 1,  GPU Memory Usage is 42G.

You can use deepspeed to reduce GPU memory, we have updated our evaluation code configured with deepspeed. With the help of deepspeed, our model can be inferred with only 22G mempory under eval_batch_size=1.

**Comment by OmarMohammed88** [comment]
@HuangZixian  
i tested it using deepspeed on 2-V100 32G and got this error

```[rank1]:     assert train_batch == micro_batch * grad_acc * self.world_size, (

[rank1]: AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * 

gradient_acc_step * world_size 1 != 1 * 1 * 2```
i even set the eval_batch_size = 1

**Comment by HuangZixian** [comment]
@OmarMohammed88 

This is an error caused by deepspeed's configuration, I updated the "run_evaluation.py"  to add code to check the number of GPUs, please test it again.

Many thanks for your feedback!

**Comment by OmarMohammed88** [comment]
Got new error ```AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'```
Despite i  installed the envi requirements

**Comment by HuangZixian** [comment]
Is this caused by the mismatch between the CUDA version and the pytorch version? 

My CUDA version is 11.8 and torch==2.2.0+cu118.
