### ISSUE TITLE
XCSQA Experiment

### ISSUE THREAD

**Issue by fmm170** [CONE-MT/MindMerger#3]
Thank you for this wonderful work. In the code repository, I did not find the evaluation script for the X-CSQA dataset. I was wondering if the evaluation code for XCSQA will be open-sourced? Thank you!

**Comment by HuangZixian** [comment]
Thank you for your attention!

Yes, we're doing it. We will public the fine-tuned CSQA-Llama to HuggingFace first, and then release our model and code.
